Add some more json fields
bonedaddy/go-blocknative pull request #7
Opened 2021-04-13 13:09 UTC by krasi-georgiev

Error Reason
Tx Timestamp
Tx PendingTimeStamp

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

2021-04-14 19:31 UTC, bonedaddy requested changes
Looks good but the mutex needs to be added back due to concurrency concerns with gorilla.

2021-04-14 19:31 UTC, bonedaddy commented on client/client.go
> -	mx      sync.RWMutex
the mutex is needed due to gorilla. [see here](https://pkg.go.dev/github.com/gorilla/websocket?utm_source=godoc#hdr-Concurrency)

2021-04-15 08:51 UTC, krasi-georgiev commented on client/client.go
> -	mx      sync.RWMutex
yeah, any idea how to fix the blocking during shutdown? The issue is that because of the mtx can't write a message.

But reading the info it seems that if we have 2 mutexes - one for reading and one for writing it should work. what you think?

2021-04-16 11:20 UTC, krasi-georgiev commented
opened another PR as I moved the repo
https://github.com/bonedaddy/go-blocknative/pull/8

2021-04-16 11:20 UTC, closed without merging